name: "Lab 02"
on: push
jobs:
    build-app:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - id: build-dotnet
              uses: ./.github/actions/build-dotnet-app
              with:
                folder-path: apps/uptodate-app
            - name: Publish Artifact
              uses: actions/upload-artifact@v4
              with:
                name: dotnet-app
                path: ${{ steps.dotnet-build.outputs.output-directory-path }}
