name: "Lab 02"
on: push
env:
    MY_VARIABLE: Hello, GitHub Actions!
jobs:
    say-hello:
        runs-on: ubuntu-latest
        steps:
            - id: needed
              uses: wjr-/ci-security/build-dotnet-app@main
              with:
                folder-path: app/uptodate-app
